### Data Processing Notebook
Clean, Transform, and Prepare Your Dataset for Analysis

In [1]:
import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 20)
pd.set_option("display.width", 120)

### Load Dataset

In [2]:
df = pd.read_csv('../data/example/bmw.csv')
print(f"Dataset Loaded: {df.shape[0]:,} rows × {df.shape[1]} columns\n")
df.head()

Dataset Loaded: 3,072 rows × 11 columns

,Year,Month,Region,Model,Units_Sold,Avg_Price_EUR,Revenue_EUR,BEV_Share,Premium_Share,GDP_Growth,Fuel_Price_Index
0,2018,1,Europe,3 Series,7822,47482,371404204,0.011,19.12,3.5,1.0
1,2018,1,Europe,5 Series,10280,61685,634121800,0.019,19.12,3.5,1.0
2,2018,1,Europe,X3,3105,58433,181434465,0.022,19.12,3.5,1.0
3,2018,1,Europe,X5,7420,67955,504226100,0.021,19.12,3.5,1.0
4,2018,1,Europe,X7,8474,92300,782150200,0.035,19.12,3.5,1.0

### Quick Overview

In [3]:
print("Data Types")
print(df.dtypes.to_string())
print()
print("Missing Values Per Column")
nulls = df.isnull().sum()
nulls_pct = (nulls / len(df) * 100).round(2)
missing_info = pd.DataFrame({"Missing": nulls, "% of Total": nulls_pct})
print(missing_info[missing_info["Missing"] > 0].to_string() if nulls.sum() > 0 else "No Missing Values Found!")
print()
print(f"Duplicate Rows: {df.duplicated().sum():,}")
print(f"Total Rows:     {len(df):,}")

Data Types
Year                  int64
Month                 int64
Region               object
Model                object
Units_Sold            int64
Avg_Price_EUR         int64
Revenue_EUR           int64
BEV_Share           float64
Premium_Share       float64
GDP_Growth          float64
Fuel_Price_Index    float64

Missing Values Per Column
No Missing Values Found!

Duplicate Rows: 0
Total Rows:     3,072


### 1. Handle Missing Values

In [4]:
column = "Month"  # NOTE: please change to column name
strategy = "mean" # NOTE: options -> mean, median, mode, constant, drop
constant_value = 0 # NOTE: please change if strategy is "constant"

before_nulls = df[column].isnull().sum()
print(f"Before: '{column}' has {before_nulls} Missing Value(s)")

if before_nulls == 0:
    print("→ No Missing Values — Nothing To Do!")
else:
    if strategy == "mean":
        df[column] = df[column].fillna(df[column].mean())
    elif strategy == "median":
        df[column] = df[column].fillna(df[column].median())
    elif strategy == "mode":
        df[column] = df[column].fillna(df[column].mode()[0])
    elif strategy == "constant":
        df[column] = df[column].fillna(constant_value)
    elif strategy == "drop":
        df = df.dropna(subset=[column])

    after_nulls = df[column].isnull().sum()
    print(f"After:  '{column}' has {after_nulls} Missing Value(s)")
    print(f"{before_nulls - after_nulls} Null(s) Handled Using '{strategy}'")

print(f"\nDataset Shape: {df.shape[0]:,} rows × {df.shape[1]} columns")

Before: 'Month' has 0 Missing Value(s)
→ No Missing Values — Nothing To Do!

Dataset Shape: 3,072 rows × 11 columns

### Remove Duplicate Rows

In [5]:
subset_cols = None # NOTE: specify columns to check for duplicates (e.g., ["col1", "col2"]) or set to None to check all columns
keep = "first" # NOTE: "first" (keep first occurrence), "last" (keep last occurrence), False (drop all duplicates)

before = len(df)
df = df.drop_duplicates(subset=subset_cols, keep=keep)
removed = before - len(df)

print(f"Before: {before:,} rows")
print(f"After:  {len(df):,} rows")
print(f"Removed {removed:,} duplicate row(s)")

Before: 3,072 rows
After:  3,072 rows
Removed 0 duplicate row(s)


### Rename / Drop Columns

3a. Rename a Column

In [6]:
old_name = "Month"
new_name = "Month_Num"

if old_name not in df.columns:
    print(f"Column '{old_name}' Not Found! Available: {list(df.columns)}")
elif new_name in df.columns:
    print(f"Column '{new_name}' Already Exists!")
else:
    df = df.rename(columns={old_name: new_name})
    print(f"'{old_name}' → '{new_name}'")

print(f"Columns: {list(df.columns)}")

'Month' → 'Month_Num'
Columns: ['Year', 'Month_Num', 'Region', 'Model', 'Units_Sold', 'Avg_Price_EUR', 'Revenue_EUR', 'BEV_Share', 'Premium_Share', 'GDP_Growth', 'Fuel_Price_Index']

3b. Drop a Column

In [7]:
drop_column = "Region"

if drop_column not in df.columns:
    print(f"Column '{drop_column}' Not Found! Available: {list(df.columns)}")
else:
    df = df.drop(columns=[drop_column])
    print(f"Column '{drop_column}' Dropped! {len(df.columns)} Column(s) Remaining!")

print(f"Columns: {list(df.columns)}")

Column 'Region' Dropped! 10 Column(s) Remaining!
Columns: ['Year', 'Month_Num', 'Model', 'Units_Sold', 'Avg_Price_EUR', 'Revenue_EUR', 'BEV_Share', 'Premium_Share', 'GDP_Growth', 'Fuel_Price_Index']

### Final Dataset Preview

In [8]:
print(f"Shape: {df.shape[0]:,} rows × {df.shape[1]} columns")
print(f"Missing values: {df.isnull().sum().sum()}")
print(f"Duplicate rows: {df.duplicated().sum()}")
print()
df.head(10)

Shape: 3,072 rows × 10 columns
Missing values: 0
Duplicate rows: 0

,Year,Month_Num,Model,Units_Sold,Avg_Price_EUR,Revenue_EUR,BEV_Share,Premium_Share,GDP_Growth,Fuel_Price_Index
0,2018,1,3 Series,7822,47482,371404204,0.011,19.12,3.50,1.00
1,2018,1,5 Series,10280,61685,634121800,0.019,19.12,3.50,1.00
2,2018,1,X3,3105,58433,181434465,0.022,19.12,3.50,1.00
3,2018,1,X5,7420,67955,504226100,0.021,19.12,3.50,1.00
4,2018,1,X7,8474,92300,782150200,0.035,19.12,3.50,1.00
5,2018,1,i4,10607,64082,679717774,0.035,19.12,3.50,1.00
6,2018,1,iX,4805,73975,355449875,0.016,19.12,3.50,1.00
7,2018,1,MINI,2554,43005,109834770,0.013,19.12,3.50,1.00
8,2018,1,3 Series,3826,48068,183908168,0.021,17.60,2.37,1.02
9,2018,1,5 Series,7498,62435,468137630,0.015,17.60,2.37,1.02

### Export Processed Dataset

In [9]:
output_path = "../data/processed/bmw.csv"
df.to_csv(output_path, index=False)
print(f"Saved to '{output_path}' ({df.shape[0]:,} rows × {df.shape[1]} columns)")

Saved to '../data/processed/bmw.csv' (3,072 rows × 10 columns)